#+TITLE: Auto trader

The initial idea was to make a simple automated trader program.
I came back from that idea and just decided to make an analyzing program
that figure out which shares will be good to buy.

An initial attempt was made at
https://docs.google.com/spreadsheets/d/1TeGVvRAvj7H5hvim02c_Bu7TX7oDj0edTmpZjcI5zFA/edit#gid=1923839140

However google spreadsheet doesn't deal with that many requests well.
So instead we'll just cache the results. This way we can make our own shadowing
db maybe that eventually will grow bigger than the 5 years restricted by
morningstar.


* Current functionality
+ Scrape [[http://www.asx.com.au/][asx]] for semi realtime stock prices (Google finance is unreliable,
  alpha-vantage is rate limited at 1 request per second, and doesn't allow
  batch requests, see the branches).
+ Get and cache key indicators from the morningstar [[https://gist.github.com/hahnicity/45323026693cdde6a116][api]].
+ Produce a html table which is ordered by 'bargains', shares that are known to
  produce lots of dividend or profit (minimum of either) divided by price.

  I also played around with the IG api but it's poorly documented
  (what is an EPIC for example)
  so the main program is in the analyze folder. just run =make run=.
  
  the html result has links to the reuters page so you can verify it's indeed a
  good idea to buy.
  There is also a link to the anouncements page of asx.
  
  Note that the morningstar stuff is cached, because it takes ages to run that
  for the first time. I also had the idea of making an append like thing from
  the cached but haven't gotten to do that.
* Possible extensions.
  Morining star provides a historic dividend that goes much farther back then 5
  years. we can use this to calculate a much more precise anuity than just the
  5 year one.
  EG:
  http://globalquote.morningstar.com/globalcomponent/RealtimeHistoricalStockData.ashx?ticker=XASX:BHP&showVol=true&dtype=his&f=d&curry=USD&range=1980-1-1|2014-10-10&isD=true&isS=true&hasF=true&ProdCode=DIRECT
  

